[{"id"=>"T5279800-1",
  "partOfSpeech"=>"noun",                                                       
  "attributionText"=>                                                           
   "from The American Heritage® Dictionary of the English Language, 5th Edition.",                                                                              
  "sourceDictionary"=>"ahd-5",                                                  
  "text"=>                                                                      
   "A widely cultivated plant <em>(Solanum lycopersicum</em> syn. <em>Lycopersicon esculentum)</em> in the nightshade family, having edible, fleshy, usually red fruit. Tomatoes are native to and were first domesticated in northern South America.",                                                                         
  "sequence"=>"1",                                                              
  "score"=>0,                                                                   
  "labels"=>[],                                                                 
  "citations"=>[],                                                              
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://ahdictionary.com/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"id"=>"T5279800-2",
  "partOfSpeech"=>"noun",
  "attributionText"=>
   "from The American Heritage® Dictionary of the English Language, 5th Edition.",
  "sourceDictionary"=>"ahd-5",
  "text"=>"The fruit of this plant.",
  "sequence"=>"2",
  "score"=>0,
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://ahdictionary.com/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>"from The Century Dictionary.",
  "sourceDictionary"=>"century",
  "text"=>
   "The fruit of a garden vegetable, <em>Lycopersicum esculentum</em>, native in tropical South America, now widely cultivated for its esculent fruit in temperate as well as tropical lands; also, the plant itself.",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://www.wordnik.com/colophon#century/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>"from The Century Dictionary.",
  "sourceDictionary"=>"century",
  "text"=>
   "See <internalXref urlencoded=\"Cyphomandra\">Cyphomandra</internalXref>.",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://www.wordnik.com/colophon#century/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "The fruit of a plant of the Nightshade family (<spn>Lycopersicum esculentun</spn>); also, the plant itself. The fruit, which is called also <altname>love apple</altname>, is usually of a rounded, flattened form, but often irregular in shape. It is of a bright red or yellow color, and is eaten either cooked or uncooked.",
  "labels"=>[{"text"=>"(Bot.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "a large gall consisting of a mass of irregular swellings on the stems and leaves of grapevines. They are yellowish green, somewhat tinged with red, and produced by the larva of a small two-winged fly (<spn>Lasioptera vitis</spn>).",
  "labels"=>[{"text"=>"(Zoöl.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "the adult or imago of the tomato worm. It closely resembles the tobacco hawk moth. Called also <altname>tomato hawk moth</altname>. See <ex>Illust.</ex> of <er>Hawk moth</er>.",
  "labels"=>[{"text"=>"(Zoöl.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "the larva of a large hawk moth (<spn>Manduca quinquemaculata</spn>, <spn>Protoparce quinquemaculata</spn>, <spn>Sphinx quinquemaculata</spn>, or <spn>Macrosila quinquemaculata</spn>) which feeds upon the leaves of the tomato and potato plants, often doing considerable damage. Called also <altname>tomato hornworm</altname> and <altname>potato worm</altname>, and in the Southern U. S. <altname>tobacco fly</altname>.",
  "labels"=>[{"text"=>"(Zoöl.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>
   "A widely <xref>cultivated</xref> <xref>plant</xref>, Solanum lycopersicum, having <xref>edible</xref> <xref>fruit</xref>",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>
   "The savory <xref>fruit</xref> of this plant, red when ripe, treated as a <xref>vegetable</xref> in <xref>horticulture</xref>",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"A shade of <xref>red</xref>, the colour of a ripe tomato.",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"A desirable-looking woman.",
  "labels"=>[{"text"=>"slang", "type"=>"register"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"A stupid act or person.",
  "labels"=>[{"text"=>"slang", "type"=>"register"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"verb",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"to <xref>pelt</xref> with tomatoes",
  "labels"=>[{"text"=>"transitive", "type"=>"grammar"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"verb",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"to add tomatoes to (a dish)",
  "labels"=>[{"text"=>"transitive", "type"=>"grammar"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from WordNet 3.0 Copyright 2006 by Princeton University. All rights reserved.",
  "sourceDictionary"=>"wordnet",
  "text"=>"mildly acid red or yellow pulpy fruit eaten as a vegetable",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://wordnet.princeton.edu/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from WordNet 3.0 Copyright 2006 by Princeton University. All rights reserved.",
  "sourceDictionary"=>"wordnet",
  "text"=>"native to South America; widely cultivated in many varieties",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://wordnet.princeton.edu/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"}]
=> 
[{"id"=>"T5279800-1",
  "partOfSpeech"=>"noun",
  "attributionText"=>
   "from The American Heritage® Dictionary of the English Language, 5th Edition.",
  "sourceDictionary"=>"ahd-5",
  "text"=>
   "A widely cultivated plant <em>(Solanum lycopersicum</em> syn. <em>Lycopersicon esculentum)</em> in the nightshade family, having edible, fleshy, usually red fruit. Tomatoes are native to and were first domesticated in northern South America.",
  "sequence"=>"1",
  "score"=>0,
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://ahdictionary.com/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"id"=>"T5279800-2",
  "partOfSpeech"=>"noun",
  "attributionText"=>
   "from The American Heritage® Dictionary of the English Language, 5th Edition.",
  "sourceDictionary"=>"ahd-5",
  "text"=>"The fruit of this plant.",
  "sequence"=>"2",
  "score"=>0,
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://ahdictionary.com/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>"from The Century Dictionary.",
  "sourceDictionary"=>"century",
  "text"=>
   "The fruit of a garden vegetable, <em>Lycopersicum esculentum</em>, native in tropical South America, now widely cultivated for its esculent fruit in temperate as well as tropical lands; also, the plant itself.",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://www.wordnik.com/colophon#century/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>"from The Century Dictionary.",
  "sourceDictionary"=>"century",
  "text"=>
   "See <internalXref urlencoded=\"Cyphomandra\">Cyphomandra</internalXref>.",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://www.wordnik.com/colophon#century/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "The fruit of a plant of the Nightshade family (<spn>Lycopersicum esculentun</spn>); also, the plant itself. The fruit, which is called also <altname>love apple</altname>, is usually of a rounded, flattened form, but often irregular in shape. It is of a bright red or yellow color, and is eaten either cooked or uncooked.",
  "labels"=>[{"text"=>"(Bot.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "a large gall consisting of a mass of irregular swellings on the stems and leaves of grapevines. They are yellowish green, somewhat tinged with red, and produced by the larva of a small two-winged fly (<spn>Lasioptera vitis</spn>).",
  "labels"=>[{"text"=>"(Zoöl.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "the adult or imago of the tomato worm. It closely resembles the tobacco hawk moth. Called also <altname>tomato hawk moth</altname>. See <ex>Illust.</ex> of <er>Hawk moth</er>.",
  "labels"=>[{"text"=>"(Zoöl.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from the GNU version of the Collaborative International Dictionary of English.",
  "sourceDictionary"=>"gcide",
  "text"=>
   "the larva of a large hawk moth (<spn>Manduca quinquemaculata</spn>, <spn>Protoparce quinquemaculata</spn>, <spn>Sphinx quinquemaculata</spn>, or <spn>Macrosila quinquemaculata</spn>) which feeds upon the leaves of the tomato and potato plants, often doing considerable damage. Called also <altname>tomato hornworm</altname> and <altname>potato worm</altname>, and in the Southern U. S. <altname>tobacco fly</altname>.",
  "labels"=>[{"text"=>"(Zoöl.)", "type"=>"fld"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://gcide.gnu.org.ua/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>
   "A widely <xref>cultivated</xref> <xref>plant</xref>, Solanum lycopersicum, having <xref>edible</xref> <xref>fruit</xref>",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>
   "The savory <xref>fruit</xref> of this plant, red when ripe, treated as a <xref>vegetable</xref> in <xref>horticulture</xref>",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"A shade of <xref>red</xref>, the colour of a ripe tomato.",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"A desirable-looking woman.",
  "labels"=>[{"text"=>"slang", "type"=>"register"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"A stupid act or person.",
  "labels"=>[{"text"=>"slang", "type"=>"register"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"verb",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"to <xref>pelt</xref> with tomatoes",
  "labels"=>[{"text"=>"transitive", "type"=>"grammar"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"verb",
  "attributionText"=>
   "from Wiktionary, Creative Commons Attribution/Share-Alike License.",
  "sourceDictionary"=>"wiktionary",
  "text"=>"to add tomatoes to (a dish)",
  "labels"=>[{"text"=>"transitive", "type"=>"grammar"}],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"http://creativecommons.org/licenses/by-sa/3.0/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from WordNet 3.0 Copyright 2006 by Princeton University. All rights reserved.",
  "sourceDictionary"=>"wordnet",
  "text"=>"mildly acid red or yellow pulpy fruit eaten as a vegetable",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://wordnet.princeton.edu/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"},
 {"partOfSpeech"=>"noun",
  "attributionText"=>
   "from WordNet 3.0 Copyright 2006 by Princeton University. All rights reserved.",
  "sourceDictionary"=>"wordnet",
  "text"=>"native to South America; widely cultivated in many varieties",
  "labels"=>[],
  "citations"=>[],
  "word"=>"tomato",
  "relatedWords"=>[],
  "exampleUses"=>[],
  "textProns"=>[],
  "notes"=>[],
  "attributionUrl"=>"https://wordnet.princeton.edu/",
  "wordnikUrl"=>"https://www.wordnik.com/words/tomato"}]
